### ISSUE TITLE
Is Normal Fixed Addressing mode supported?

### ISSUE THREAD

**Issue by danielfu11** [pylessard/python-udsoncan#103]
Hi,

Is Normal Fixed Addressing mode supported? i.e. just using source address and target address. No txid or rxid needed.

**Comment by pylessard** [comment]
Absolutely.
See how to define all types of addresses : https://can-isotp.readthedocs.io/en/latest/isotp/examples.html#different-type-of-addresses

You can pass an Address object to the TransportLayer (or CanStack).

Regards

**Comment by pylessard** [comment]
And more details about Address object here: https://can-isotp.readthedocs.io/en/latest/isotp/addressing.html

**Comment by danielfu11** [comment]
Ahh yes I should have read the documentation more closely, thanks @pylessard!
