### ISSUE TITLE
MemoryLocation memorysize_format

### ISSUE THREAD

**Issue by Anthony-Tatowicz** [pylessard/python-udsoncan#11]
Running udsoncan==1.5 

I found that the memorysize_format param of MemoryLocation doesn't change the format of the data sent on the bus, the only way to get the format to change is by defining it in the config before hand.

Looking into the issue, you may have quick fix though?

**Comment by pylessard** [comment]
Interesting. Will look Sunday. This should be covered by unit tests. Can you share a piece of code and a log?

**Comment by pylessard** [comment]
I think I found the cause. Copy paste of code that went wrong. 
Will push a fix today. But will release something including unit tests only this weekend.

**Comment by pylessard** [comment]
Should be fixed now in branch master. I haven't tested at all, just blindly submitted changes to be quick.
Cheers

**Comment by Anthony-Tatowicz** [comment]
Tested, looks good. Ill close out this issue.

**Comment by pylessard** [comment]
Fixed in v1.6
