### ISSUE TITLE
Functionality for CAN-FD

### ISSUE THREAD

**Issue by Ahelion** [pylessard/python-udsoncan#116]
General question(not quite issues):
Background: I can set up the Bus ( vector ) as CAN_FD, but when the message is send via client.read_data_by_id the Baud Rate Switch BIT is not set.
Is there something extra to do for the client?
Checked with CANOE for logging only.

**Comment by pylessard** [comment]
Do you use Python-can?  If you do, you must set the flag is_fd=true when sending a message.  If you use the PythonCanIsoTPconenction, there's an option in the TransportLayer to automatically set that flag. 

See : https://can-isotp.readthedocs.io/en/latest/isotp/implementation.html#can_fd

**Comment by pylessard** [comment]
You must set the option on the TransportLayer. I gave you a link to the aprameter definition. Read what I wrote.

**Comment by pylessard** [comment]
With python-can, you can use a Can-fd bus to send normal message. So you also need to set a flag on each message. I think this is what confuses you.

**Comment by Ahelion** [comment]
I did not forget, just waiting for HW to free up, for me to test it.

**Comment by pylessard** [comment]
shall we close this issue?

**Comment by Ahelion** [comment]
> shall we close this issue?

YES! thank you very much

**Comment by Affenselfie** [comment]
Hey,

I found this issue while struggling to get CAN-FD working. Below is the code I used for a working `udsoncan`  CAN-FD setup, which may help others:
```python
# Refer to isotp documentation for full details about parameters
isotp_params = {
 'tx_padding': 0x55,                    # Will pad all transmitted CAN messages with byte 0x00.
 'can_fd': True,                        # Does not set the can_fd flag on the output CAN messages
 'bitrate_switch': True,                # Does not set the bitrate_switch flag on the output CAN messages
 'tx_data_length': 64,
 'tx_data_min_length': 8
}



bus = can.Bus(channel='can0', interface='socketcan', fd=True)       # Link Layer (CAN protocol)
notifier = can.Notifier(bus, [])                            # Add a debug listener that print all messages
tp_addr = isotp.Address(isotp.AddressingMode.Normal_29bits, txid=0x18DA0BFA, rxid=0x18DAFA0B) # Network layer addressing scheme
stack = isotp.NotifierBasedCanStack(bus=bus, notifier=notifier, address=tp_addr, params=isotp_params)  # Network/Transport layer (IsoTP protocol). Register a new listenenr
conn = PythonIsoTpConnection(stack)

with Client(
    conn,
    request_timeout=5,
    config={"p2_star_timeout": 5, "p2_timeout": 5, "use_server_timing": False},
) as client:
        client.change_session(1)
```
