### ISSUE TITLE
Work to support for Intrepid's CAN interfaces?

### ISSUE THREAD

**Issue by syntroniks** [pylessard/python-udsoncan#12]
The python-ics interface (provided by Intrepid Control Systems) handles ISO-TP timing, but in Windows it does not provide a socketcan type interface.

How realistic would it be to add support for these ValueCAN/neo* devices under Windows?
Sample API snippets:
`device = ics.find_devices()[0]`
`ics.open_device(device)`
`ics.iso15765_enable_networks(device, ics.NETID_HSCAN)`

I've written some small helpers to work with exchanges but I would love to leverage your service definitions.
```
    def iso_exchange(self, req_address, rsp_address, message):
        ics.iso15765_enable_networks(self.device, ics.NETID_HSCAN)
        self.rx_iso_setup(req_address, rsp_address)
        self.tx_iso(req_address, message)
        ret = self.rx(rsp_address)
        ics.iso15765_disable_networks(self.device)
        return ret```

**Comment by pylessard** [comment]
Hello, I've never heard of these device. If they support IsoTP and are manageable through Python, it would be very realistic (and most likely easy) to support them.

Can you share everything you have so far around this. Documentation, code, example, 
Etc.

How much do you want to be involved in the process of supporting this? I don't own such device, so a tester will be needed

**Comment by syntroniks** [comment]
The devices are manufactured by https://www.intrepidcs.com/
The ValueCAN3 and neoFIRE/RED are some of their more popular products (I have both available for test).
Their software, Vehicle Spy is a multi-protocol analyzer (similar to wireshark with transmit capability)

They offer an API DLL, icsneo40.dll that has a number of interfaces to other languages

More info: https://cdn.intrepidcs.net/support/neoVIDLL/neoVIDLLhelpdoc.html
Their short page on *NIX support: https://cdn.intrepidcs.net/support/neoVIDLL/neoVIDLLhelpdoc.html

I am available for development & test. I imagine this effort will require adding a new class to 'connections.py'
```
conn = IcsNeoVIConnection(interface='131720', rxid=0x001, txid=0x002)
conn.open()
...etc
```

**Comment by pylessard** [comment]
Correct, we could add a new Connection to which we pass some sort of handle pointing to the hardware.
Since you have the interface, it would probably more efficient if you write the Connection. I will read the doc this weekend and propose somehingon my side. I see that they have a[ Python module](https://github.com/intrepidcs/python_ics) to itnerract with the DLL. If this works fine, it should be a piece of cake to implement a new Connection.

**Comment by syntroniks** [comment]
Do you want tests? I don't have a mock interface, but my tests with a real hardware interface do pass.

**Comment by syntroniks** [comment]
Hey for what it's worth, python-can seems to have support for these devices as well
https://python-can.readthedocs.io/en/master/interfaces/neovi.html
I didn't see that until just now but it looks like your repo isn't yet compatible with using python-can

**Comment by pylessard** [comment]
@syntroniks I have some preliminary work completed and uploaded but not released and not documented. Release is coming soon, but if you feel like testing early, you can grab the latest of python-can-isotp and udsoncan from github and try the `PythonIsoTpConnection`.  

Cheers

**Comment by pylessard** [comment]
V1.7 is released and supports python-can. 
Closing this.
