### ISSUE TITLE
[CANFD, IsoTPSocketConnection] How to set the link layer options to CANFD

### ISSUE THREAD

**Issue by ziyangfu** [pylessard/python-udsoncan#122]
Hi
    We use IsoTPSocketConnection to connect underlying protocol. as we all known,  the default values about link layer is CAN2.0, if we need change link layer to CANFD，whether we need add some codes in connection->IsoTPSocketConnection->open() like this:
`self.tpsock.set_ll_opts(CAN_FD, 64)`
    if not necessary, we don't want to modifiy your code. Thanks.
> the python_isotp manual
[socket.set_ll_opts(mtu=None, tx_dl=None, tx_flags=None)](https://can-isotp.readthedocs.io/en/latest/isotp/socket.html#socket.set_ll_opts)

**Comment by pylessard** [comment]
Hi, you can pass your own socket to the connection object.

See https://github.com/pylessard/python-udsoncan/blob/beabbf2c1e0d5e0d0627650f02410bc0487cc2a2/udsoncan/connections.py#L250

**Comment by ziyangfu** [comment]
Hi, pylessard
    thanks for your answer，I got it.
