### ISSUE TITLE
Does python-udsoncan support CAN FD ?

### ISSUE THREAD

**Issue by MilLad369** [pylessard/python-udsoncan#133]
I was trying to use this library on CAN-FD implementation, but I got an error that extended ID is not supported. 
Did I miss something or this library is not yet supporting CAN-FD

Thank you in advance 
Regards
Miles

**Comment by pylessard** [comment]
udsoncan repo is not aware of the underlying layer. You can make it work on TCP/IP if you want.

If you use the PythonCanIsoTpConnection taht make usage of the [python-can-isotp](https://github.com/pylessard/python-can-isotp) module, then the answer is yes. It's fully compliant with CAN FD.

**Comment by pylessard** [comment]
does that answer the question?
