### ISSUE TITLE
How to specify a functional request?

### ISSUE THREAD

**Issue by zhuyu4839** [pylessard/python-udsoncan#134]

**Comment by zhuyu4839** [comment]
And how to config functional ID by python-can-isotp?

**Comment by pylessard** [comment]
https://can-isotp.readthedocs.io/en/latest/isotp/examples.html#sending-with-functional-addressing-broadcast

**Comment by zhuyu4839** [comment]
I mean by python-udsoncan

**Comment by pylessard** [comment]
Ha. You can change the TransportLayer object config default request type and change it back once you are done.

https://can-isotp.readthedocs.io/en/latest/isotp/implementation.html#default_target_address_type

**Comment by pylessard** [comment]
Shall we close this?
