### ISSUE TITLE
How to run python-udsoncan

### ISSUE THREAD

**Issue by ghost** [pylessard/python-udsoncan#136]
Hi, I have implemented UDS services in application code, and need to test all UDS service id.
I am planning to use your python(python-udsoncan) script for UDS testing.
how to run your python-udsoncan script for UDS testing?

Thanks in advance.
Aajai.

**Comment by pylessard** [comment]
Care to be more specific with your questions?
I wrote documentation to explain how to use the project. Maybe start by reading it?

**Comment by Aajaivn** [comment]
Hello, I read documentation, but still not clear which python file should run for UDS service testing ?
Please can you point out in document.

**Comment by pylessard** [comment]
Hi, I will put as much effort in my answers as you put effort in writing your questions. 
Right now you made none, so I making none.

Be more specific, ask an actual questions. Show what you did. Tell what you don't understand. Then maybe I can answer something.

**Comment by Kaeptn-G** [comment]
> Hi, I have implemented UDS services in application code, and need to test all UDS service id. I am planning to use your python(python-udsoncan) script for UDS testing. how to run your python-udsoncan script for UDS testing?
> 
> Thanks in advance. Aajai.

Mate, I think you misunderstood what python-udsoncan actually is. Seema like you are searching for a ready-to-run application, but this is more a library which helps you to habdle all the protocol stuff. The app using this library, needs to be created by you. 
Was this what you were missing?

**Comment by pylessard** [comment]
I will close this issue as it is empty in content.
