### ISSUE TITLE
Client throws an exception for response pending responses

### ISSUE THREAD

**Issue by syntroniks** [pylessard/python-udsoncan#14]
Code in question: https://github.com/pylessard/python-udsoncan/blob/fd7e34960eb2f1bbb4e0cea1a110e2a5c1328af6/udsoncan/client.py#L1441-L1444

**How would you like to handle 'ResponsePending (0x78)' handling by the client?**

In my instance, I am entering a programming session:
```
conn = IcsNeoVIConnection(serial=None, rxid=0x7E9, txid=0x7E1)
with Client(conn,  request_timeout=2, config=config) as client:
    client.change_session(udsoncan.services.DiagnosticSessionControl.Session.programmingSession)
```
![image](https://user-images.githubusercontent.com/5464081/49735400-c2294a00-fc4c-11e8-816a-50a7bc50aedb.png)

**Who/What should be responsible for handling these "response pending" scenarios?**

**Comment by pylessard** [comment]
What you are seeing is the wanted behaviour, you can catch the exception and handle based on response code. You can also disable exceptions for negative responses, but you will still need to manage the errot code
