### ISSUE TITLE
Increase bytes of a memorylocation.

### ISSUE THREAD

**Issue by zhongpipi** [pylessard/python-udsoncan#144]
udsoncan/__init__.py  class AddressAndLengthFormatIdentifier.
Can we increase more possible values of memsize_map? Like 
{
            8 : 1,
            16 : 2,
            24 : 3,
            32 : 4,
            40 : 5
    }

**Comment by zhongpipi** [comment]
Hi, after updating to version 1.6, this issue has been solved. 
Thank you so much for developing UDSonCAN library! !

**Comment by pylessard** [comment]
Thank you 
Indeed a duplicate of #140
