### ISSUE TITLE
Getting Raw payload

### ISSUE THREAD

**Issue by Aziz-repo** [pylessard/python-udsoncan#148]
I'm trying to read DTC from an ECU and I'm getting a positive Response. When I print the response it just prints the name of the class.
My Question is: How can I get the raw data from the response object ?
I checked the `from_payload()` and `get_payload()` but I don't think it's the right approach to get it done.

**Comment by pylessard** [comment]
Hi. 
DTC parsing works but lacks documentation.

`response.data` gives the raw payload.
If you used the client object, the payload will be parsed in  `response.service_data`.

You can use IPython to inspect the content of the data. Or just print the object with `print(response service_data.__dict__`

Finally, the unit tests are a good source of examples.

Cheers

**Comment by Aziz-repo** [comment]
Thank you for the fast reply!!

As I understand the source code, there is a nested class called `ResponseData` and it's attributes are specific to each service.
I think it's well documented, I just stumped on it after opening the thread but thank you for the advice :blush:

**Comment by pylessard** [comment]
Shoul we keep this thread open?

**Comment by Aziz-repo** [comment]
Yes,
I'm closing this thread for no issue to be solved.
