### ISSUE TITLE
Can BaseService become part of the public API?

### ISSUE THREAD

**Issue by lumagi** [pylessard/python-udsoncan#154]
Hi,

I noticed that you moved the `BaseService` in #150. After seeing #149 get merged, I wanted to ask if the `BaseService` is now part of the public API and this is its final resting place or if you could be moved to make it part of the public API due to #149?

Regards,
Lukas

**Comment by pylessard** [comment]
I moved BaseService because I had a circular dependecy problem. That was the only solution that wouldn't break the interface.

You can import like this : `from udsoncan improt BaseService`.  Should work and be future proof

Cheers

**Comment by lumagi** [comment]
Great, thanks for the quick response.
