### ISSUE TITLE
Request timeout is integer but constructor expects boolean

### ISSUE THREAD

**Issue by prasadghole** [pylessard/python-udsoncan#161]
`    def __init__(self, conn: BaseConnection, config: ClientConfig = default_client_config, request_timeout: Optional[bool] = None):`
Client.py expects boolean but timeout should be integer.

My pyright typechecker is giving me error when I use positive integer number as timeout value.

**Comment by pylessard** [comment]
Fixed in v1.18.1. Please confirm that this issue is resolved.

**Comment by prasadghole** [comment]
Yes it is fixed in version 1.18.1
