### ISSUE TITLE
functional address with NRC 0x7f

### ISSUE THREAD

**Issue by zhaohuijun1** [pylessard/python-udsoncan#166]
Hi，How can I test fucnctional address when it  dosen‘t response NRC 0x7f ?

**Comment by pylessard** [comment]
This question is too vague

functional addressing is for broadcast. You should normally not expect a response from them. With this lib, you can set the SuppressPositiveResponse flag.  https://udsoncan.readthedocs.io/en/latest/udsoncan/client.html#suppress-positive-response

It will make the client not wait on the response
