### ISSUE TITLE
Get an error that the P2 time was timed out, but the response did not actually time out.

### ISSUE THREAD

**Issue by zhongpipi** [pylessard/python-udsoncan#170]
These are the sets of parameters I used：
`{'p2_timeout': 0.025,  
    'p2_star_timeout': 5,  
    'use_server_timing': False,}`  

`{'p2_timeout': 0.05,
    'p2_star_timeout': 5,
    'use_server_timing': False,}`

`{'p2_timeout': 0.05,
    'p2_star_timeout': 5,
    'use_server_timing': True,}`

**Comment by pylessard** [comment]
I don't understand. Please ask a better question

**Comment by pylessard** [comment]
I still have not a lot of details on your issues. But in any case, timings in the tens of milliseconds are hard to meet in the user space when relying on calls to sleep().
