### ISSUE TITLE
ascii DidCodec pass parameters

### ISSUE THREAD

**Issue by pompushko** [pylessard/python-udsoncan#184]
Hello

I know, maybe I should make own DidCodec... But! Sometimes, I have 0xFF in binary data, like data which not is filled...
Could you, please, add handling decoding errors in ascii codec?

Like `errors='replace'`

```
File "/home/username/.local/lib/python3.11/site-packages/udsoncan/common/DidCodec.py", line 70, in decode
    string_ascii = string_bin.decode('ascii')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

**Comment by pylessard** [comment]
Sorry, 0xFF is not an ASCII character, it is normal to raise an error.
If you want to tolerate it, you should make your own codec.
