### ISSUE TITLE
PythonIsoTpConnection [cilent.py]send_request() tigger TimeoutException,then ISOTP rxthread_task run isotp_send（）

### ISSUE THREAD

**Issue by caocheng7979** [pylessard/python-udsoncan#193]
run change_session(3),  goto send_request() 'self.conn.send(payload)' 
'        def specific_send(self, payload):
            if self.mtu is not None:
                if len(payload) > self.mtu:
                    self.logger.warning("Truncating payload to be set to a length of %d" % (self.mtu))
                    payload = payload[0:self.mtu]
            self.toIsoTPQueue.put(bytearray(payload)) # isotp.protocol.TransportLayer uses byte array. udsoncan is strict on bytes format
            print("send msg queue put")'
however, send_requeset() tigger TimeoutException,after that  rxthread_task() start to execute.
![uds](https://github.com/pylessard/python-udsoncan/assets/20571821/352acfb1-c5cf-44ba-89f6-3899be09b5be)

![uds2](https://github.com/pylessard/python-udsoncan/assets/20571821/3c23bb60-6290-49a5-8c2a-439786b19a6d)

![uds3](https://github.com/pylessard/python-udsoncan/assets/20571821/11a0b76b-1be4-4b2b-b41e-7b4d1587400d)

![uds4](https://github.com/pylessard/python-udsoncan/assets/20571821/3af7b216-485c-4fb9-91f1-25748250106e)

Why？Is there something wrong with the Settings？

**Comment by caocheng7979** [comment]
Thank you for your reply！
![uds5](https://github.com/pylessard/python-udsoncan/assets/20571821/bbdc53d4-0857-4394-aa8d-08c11b606663)
![uds6](https://github.com/pylessard/python-udsoncan/assets/20571821/1fe2d9f5-17c0-47b4-8391-2b604f3816c4)
My device is the ZLGCan，I turn on the Can device and start the receiving thread.
```
    if self.cmbUDSEnable.get() == 'YES':
        self.udsclient.open()
        self._terminated = False
```
After send() is called ,The msg has been put into the queue.
···
    log info:**send msg queue put**
···
But rxthread_task  seems to be blocked.
main thread TIMEOUT，rxthread_task start calling isotp_send().
```
    toIsoTPQueue queue size is now 0
    Sending xxxx
    Receiving:xxx
    fromIsoTPQueue queue size is now 1
```
something wrong with threading?

**Comment by pylessard** [comment]
I suspect you zcan lib to takes ownership of the GIL and not release it. Preventing any thread to work during that time.
Can you make an experiment for me?

make a simple thread that prints to the console in a loop. And try calling you zcan function, See if it stops the thread.


```python
import threading
import time
stop_event = threading.Event()

def func:
    while not stop_event.is_set():
        print("%s Thread: Still running" % time.time())
        time.sleep(0.1)

def main():
    t = threading.thread(target=func)
    t.start()
    time.sleep(0.5)
    try:
        printf("%s Main thread: Sending a zcan message" % time.time())
        zcan.Transmit(...)
        printf("%s Main thread: Sending a zcan message" % time.time())
        #...  Test each function.  Then see if the thread ever stops for a long time.
    finally:
        stop_event.set()
        t.join()

```

**Comment by caocheng7979** [comment]
zcan lib 
I found out why the problem happened.
I want to output log to textbox.
```
        self.logger = logging.getLogger('logger')
        # self.logger.setLevel(logging.DEBUG)
        udsLogHandler = TextboxHandler(self.text_log)
        self.logger.addHandler(udsLogHandler)

        # self.isotp_layer.logger.setLevel(logging.DEBUG)
        # isotpLogHandler = TextboxHandler(self.text_log)
        # self.isotp_layer.logger.addHandler(isotpLogHandler)

        # self.udsclient.conn.logger.setLevel(logging.DEBUG)
        # connLogHandler = TextboxHandler(self.text_log)
        # self.udsclient.conn.logger.addHandler(connLogHandler)

        self.udsclient.logger.setLevel(logging.DEBUG)
        clientLogHandler = TextboxHandler(self.text_log)
        self.udsclient.logger.addHandler(clientLogHandler)
```
If I uncomment **isotp_layer.logger**，problems are going to happen.

Thanks again for your reply！

**Comment by pylessard** [comment]
Ohh, you are using a UI framework and it's the UI that takes ownership of the GIL.
You may want to consider running the isotp communication in a different process and use IPC mechanism to itnerract with the GUI

cheers

**Comment by caocheng7979** [comment]
[guilog.txt](https://github.com/pylessard/python-udsoncan/files/14035846/guilog.txt)
[pycharmlog.txt](https://github.com/pylessard/python-udsoncan/files/14035847/pycharmlog.txt)
[CANdevicelog.asc.txt](https://github.com/pylessard/python-udsoncan/files/14035848/CANdevicelog.asc.txt)

Hi!After updating udsoncan to 1.21.2 and isotp to 2.0.3, I am now using PythonIsoTpV2Connection, but the Timeout is triggered again.Now I'm using a separate thread to log to ScrolledText.

In older versions, self.udsclient.logger was set to DEBUG and the flush was successful, but it was set to INFO and a Timeout occurred.

I even removed the srrollText to stop logging.But Timeout is still triggered.

**Comment by pylessard** [comment]
If I remember correctly, your GUI framework seemed to take ownership of the GIL. That blocks every threads.
If you configure your GUI to not do that, it would be ideal. Otherwise, maybe the cleanest way is to put the transmission part into a different process and make the GUI commnunicate through IPC.
