### ISSUE TITLE
Example uses wrong import

### ISSUE THREAD

**Issue by LouBen3010** [pylessard/python-udsoncan#24]
Hi there,

in your example code you import ISOTPConnection and use ISOTPSocketConnection.
This gave me an error using your example code.

Changing the import from
```
import from udsoncan.connections import IsoTPConnection
```
to
```
import from udsoncan.connections import IsoTPSocketConnection
```
resolves the issue.

**Comment by pylessard** [comment]
Thank you. Will check soon

**Comment by pylessard** [comment]
Fixed
Thank you!
