### ISSUE TITLE
exception in threading

### ISSUE THREAD

**Issue by francosax** [pylessard/python-udsoncan#28]
hi all,
I'm using the lib with vn1610 vector hardware , during a scan of service 22 xx yy I got this exception:
    self.__recvBuffer.append(msg.data[self.__pduStartIndex:])
AttributeError: 'CanTp' object has no attribute '_CanTp__recvBuffer'
in file ....python_uds-1.0.2-py3.7.egg\uds\uds_communications\TransportProtocols\Can\CanTp.py

My script continue to run, but slowly: it sends 1 msg per second and not every 10 msec

**Comment by pylessard** [comment]
Looks like you are using another project than mine.
You seems to be using [this project](https://github.com/richClubb/python-uds).   Can't help much unless you use "udsoncan" not "uds".
