### ISSUE TITLE
Cannot use default codec to encode multiple values with client.write_data_by_identifier

### ISSUE THREAD

**Issue by pylessard** [pylessard/python-udsoncan#29]

**Comment by feversky** [comment]
change line 41 of "udsoncan\services\WriteDataByIdentifier.py" as below:
`req.data += codec.encode(*value)`

a star unpacks the sequence/collection

**Comment by ibutra** [comment]
Can you push a new Version to pip with this fix (and possibly others?)

**Comment by pylessard** [comment]
Hi,
Yes, I will do that soon

**Comment by ibutra** [comment]
Thank you very much!
Not only for the new Version but for the whole Package! It helps out a lot!

**Comment by pylessard** [comment]
Included in v1.8.1

**Comment by m31L3r** [comment]
Hi,
regarding this issue. Why not use in WriteDataByIdentifier.make_request()  function "isinstance(codec, DidCodec)" instead of "codec.__class__==DidCodec"?
That way i could also use this feature for my DidSubclass without having to redefine the encode function.

Regards

**Comment by pylessard** [comment]
Here's my thinking.
The DidCodec class, which is the base class have a default behavior to use pack strings as a convenience.  (I should have left that class abstract and make a pack codec, but that is another topic.)   expanding a tuple for a pack string make sense but for a generic codec, I cannot know if the suer wants a tuple or a series of arguments. How would you encode a tuple if the library tries to unpack it? a tuple of tuple?

I think it's better to leave the codec generic and have an explicit implementation

**Comment by m31L3r** [comment]
Ah ok I see.
Thanks for your reply!
