### ISSUE TITLE
Appropriate failure response to send on timeout?

### ISSUE THREAD

**Issue by brandonros** [pylessard/python-udsoncan#34]
If the 1-2s second timeout to wait for consecutive frames in a multi-frame message is met, what is the correct behavior:

1. send nothing, wait for device to retry
2. send 7F failure... with what value for "timeout response"?

**Comment by pylessard** [comment]
Send nothing. The frame is invalid and should not go through the transport layer to reach the application layer. The UDS layer shouldn't even be aware that an incomplete message arrived.

**Comment by pylessard** [comment]
Can this be closed?
