### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by danielhrisca** [pylessard/python-udsoncan#35]
Hello Pier,

first thank you for your work on this package!

I noticed that you use tabs instead of spaces for indentation throughout the codebase. Is it possible to switch to spaces?

**Comment by pylessard** [comment]
Hi Daniel,
I am not against it, I just need a reason for it. Why do you need this?

**Comment by danielhrisca** [comment]
It's simple really: most users set up their IDE/editors to replace tabs by spaces (most use 4 spaces / tab).

I was having problems running UDS commands over CAN-FD and needed to do some debugging (prints :D) and this really hampered my progress.

**Comment by christiansandberg** [comment]
It is generally a good idea to follow some coding guidelines, and PEP-8 is the official so there is not much reason to make up your own. The tabs were an issue for me too.

**Comment by danielhrisca** [comment]
@christiansandberg can you have a look at this issue https://github.com/pylessard/python-udsoncan/issues/36

**Comment by pylessard** [comment]
That's all I needed
![image](https://user-images.githubusercontent.com/2386969/62557571-3b615700-b845-11e9-9656-6a3f132ab3d1.png)

I didn't really made my own, I simply didn't read PEP-8 and use my editor default setting.
