### ISSUE TITLE
Support RequestFileTransfer (0x38) service

### ISSUE THREAD

**Issue by wanam** [pylessard/python-udsoncan#47]
Hello @pylessard ,

Just wanted to know if you have any plans to support `RequestFileTransfer (0x38)` service, which is defined on `ISO_FDIS_14229-1`.

**Comment by pylessard** [comment]
Hi @wanam ,
Yes, I learned recently that this was added to the latest standard. Do you need it?

**Comment by wanam** [comment]
Yes, indeed we need it.

**Comment by pylessard** [comment]
Alright, will get on it soon

**Comment by wanam** [comment]
Nice! thank you.
Let me know if you need any information.

**Comment by wanam** [comment]
Hello @pylessard,
I know it's your free time and I should not ask for ETA :) , but do you have any idea about the amount effort needed for such implementation?

Thanks again and have a good day.

**Comment by pylessard** [comment]
This won't be too long. I'll get the new standard early next week. Should be done by the weekend after that, so around March 28th. Sounds good?

**Comment by wanam** [comment]
Yes it should be fine, thanks a lot for your prompt response.

**Comment by pylessard** [comment]
Out of curiosity, are you using the 2013 or 2020 version of the standard? I just learned that a new version was published few weeks ago

**Comment by wanam** [comment]
I'm using the old one `ISO/FDIS 14229-1:2012(E)`.

**Comment by pylessard** [comment]
For your information, I've started working on this. This seems straightforward

**Comment by wanam** [comment]
I saw that you pushed some tests for this service on a RequestFileTransfer branch.

FYI a friend has pushed draft here: https://github.com/wanam/python-udsoncan/commit/fa1457be53a0f0bddbe17c32a595c4a54e4ffc3d

**Comment by pylessard** [comment]
Thanks,
I indeed pushed some test. The draft seems well written, but will of course conflict with the actual test as we do not have the same naming. I will refer to it to make sure I don't forget something.

**Comment by pylessard** [comment]
Completed. Now available in v1.11
Documentation is up to date.  Let me know what you think

**Comment by wanam** [comment]
Well done! thank you.
Will test and get to you back.

**Comment by pylessard** [comment]
Can this be closed?

**Comment by wanam** [comment]
Sorry for late reply, yes you can close it.
Thank you again.
