### ISSUE TITLE
No exception is raised when UDS server respond with no Session Params on Diagnostic Control Session Request

### ISSUE THREAD

**Issue by Rohan621** [pylessard/python-udsoncan#53]
The interpret_response method of the Diagnostic Session service does not raise an InvalidResponseException if the UDS Server respond back to with no session control params. 
https://github.com/pylessard/python-udsoncan/blob/master/udsoncan/services/DiagnosticSessionControl.py#L54

As per ISO-14229(1) Section 10.2, there is no mention of the sessionParameterRecord being optional.

**Comment by pylessard** [comment]
Thanks,
It was optional in the 2006 version, which is the standard I initially used to write to library. I will update accordingly. I guess the best approach would be to add a parameter telling what version of the standard needs to be supported.

And what version are you using, in my document, the section is 9.2, not 10.2

**Comment by Rohan621** [comment]
Hi,

I am using the 2020 version.

**Comment by pylessard** [comment]
I reopened, this need to be fixed. Just didn't have time to do it

**Comment by Rohan621** [comment]
Oops. Sorry about that. Thanks for reopening the isse 😄
