### ISSUE TITLE
Send uds command byte 0 padded with 00

### ISSUE THREAD

**Issue by mmclwd** [pylessard/python-udsoncan#55]
While sending UDS service with udsoncan library, is CAN tools is vector it worked fine, but if CAN tools is PCAN, first bytes will padded with 00, see below message information.
Time        Diff Time   Chn     ID    Name     Event Type   Dir    DLC   Data length   Data                          
 [-] 16.733302   0.000000    CAN 1   700   reqUDS   SF           Rx     0     8             [00] [02 3E 00 55 55 55 55]    
UDS protocol is based on CAN not CANFD.
So how to fix this issue? 
Many thanks!

**Comment by pylessard** [comment]
Can you share your IsoTP configuration?

**Comment by mmclwd** [comment]
Thank @pylessard, I had already fixed this issue by update python-can library, maybe because the python-can lib I used is too old.
