### ISSUE TITLE
InputOutputControlByIdentifier does not handle udsoncan.DidCodec.ReadAllRemainingData

### ISSUE THREAD

**Issue by Rohan621** [pylessard/python-udsoncan#57]
The InputOutputControlByIdentifier does not handle `udsoncan.DidCodec.ReadAllRemaining` exception which is raised when the length of a Codec is requested.
https://github.com/pylessard/python-udsoncan/blob/master/udsoncan/services/InputOutputControlByIdentifier.py#L186

This should be handled the same way as in the ReadDataByIdentifier: https://github.com/pylessard/python-udsoncan/blob/master/udsoncan/services/ReadDataByIdentifier.py#L65

**Comment by pylessard** [comment]
Correct, I forgot to propagate this feature to InputOutputControlByIdentifier, this could be implemented.  I will look at this soon.

Consider that raising ReadAllRemaining is not a behaviour defined by ISO-14229. Be carefull when using this, what you are trying to achieve may not be complient with the standard.

**Comment by Rohan621** [comment]
Thanks! And agreed, the `ReadAllRemainingData` is not a behavior defined in ISO-14229 but is a part of your package. This exception does provide us to bypass calculating the length when dealing with variable length payloads being transmitted and received between the UDS Client and Server.

Looking forward to this change! 😄

**Comment by pylessard** [comment]
Handled in release v1.13.1.  Sorry for the delay
