### ISSUE TITLE
WDBI Service Implementation

### ISSUE THREAD

**Issue by Arfaoui-Mahdi** [pylessard/python-udsoncan#81]
Hi, I'm trying to use udsoncan over PCan, I have succeeded in implementing Routine Control and RDBI services, I'm stucked now in WDBI.

Let's say that I want to execute a WDBI request with 2 params : 
1- string : ID , exemple = "0X1F8B" ... 
I managed to transform this to hex int representation with :
`int IDhex = int(ID,16)`
and pass it to the config dict to encode it to ascii(64)
`IDhex : udsoncan.AsciiCodec(64)`
so it could be acceptable by the RDBI service, thus I don't know what to do to be accepted by WDBI.

For the Data, let's say that I have `data = "015A"`, I managed to transform this to bytes format with 
`dataBytes = bytes.fromhex(data)` so the routine control service could accept it. 

Giving what I did to make these two services work, how can I implement the WDBI service with Udsoncan.
I really need your help.

PS: i'm using the client way, eg :  `response = client.write_data_by_identifier(id, data)` how can I configure id and data to make this work.

Thanks.

**Comment by pylessard** [comment]
Hi,
Have you defined a codec for that Data Identifier?

When you call `write_data_by_identifier`, the data you give is given to a codec object that you can define. The goal of that codec is convert any kind of data into a bytes payload.

See an example here : https://udsoncan.readthedocs.io/en/latest/udsoncan/examples.html#reading-a-did-with-readdatabyidentifier

**Comment by Arfaoui-Mahdi** [comment]
Hi, Thank you for your response, and I'm sorry for the late reply.
I have defined a codec : 

```
config = dict(udsoncan.configs.default_client_config)
   config['data_identifiers'] = {
      vrb : udsoncan.AsciiCodec(len(dat)),
   }
```

And now I'm getting a connection with the ECU, except that I always receive a NegativeResponse Exception, I don't know if that because of requests I'm sending or because of a bad config.

what do you think ?

**Comment by pylessard** [comment]
You use the library correctly if you are able to get a response from your device. 
A negative response is your device that refuse request. Each device is different, so I cannot tell you what is the problem.

With a NegativeResponseexception comes an error code, this may help you understand what is wrong.
Possible that you do not have access right to use this service or you are not in the right diagnostic session. Maybe your device doesn't expect ASCII format.  Only you can tell.

Good luck

**Comment by Arfaoui-Mahdi** [comment]
Thanks for your response, just one last question and i'll close the issue.
How can I detect NegativeResponseException code ?, i searched in docs, I've found a lot of other exceptions codes except NegResExc code.

**Comment by pylessard** [comment]
The response is in the exception. See https://udsoncan.readthedocs.io/en/latest/udsoncan/exceptions.html#udsoncan.exceptions.NegativeResponseException

```
    except NegativeResponseException as e:
        print("%s (%d)" % (e.response.code_name, e.response.code))
```

you can also enable loggings, you will get lots of useful details from the library.  `udsoncan.setup_logging()`

**Comment by Arfaoui-Mahdi** [comment]
Thanks a lot
