### ISSUE TITLE
RequestFileTransfer.interpret_response() incorrectly parses Filesize

### ISSUE THREAD

**Issue by trivialpursuer** [pylessard/python-udsoncan#89]
When parsing a response to a FileTransfer request with moop ReadFile, the Filesize object is incorrectly parsed if the lengthFormatIdentifier != fileSizeOrDirInfoParameterLength. I believe it's a simple copy/paste error in the parsing logic where `lfid` was not updated to `fsodipl`, so the code is assuming that the number of bytes in each filesize field is equal to the value in lfid.

**Comment by trivialpursuer** [comment]
Merged, thanks!

**Comment by pylessard** [comment]
Included in v1.14
